"""Added index to message for faster querying

Revision ID: 2226c3fe92e6
Revises: 2c50bf60d56a
Create Date: 2023-06-30 02:01:11.789616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2226c3fe92e6'
down_revision = '2c50bf60d56a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_dialogue_id_sender_type_created_at', 'messages', ['dialogue_id', 'sender_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_dialogue_id_sender_type_created_at', table_name='messages')
    # ### end Alembic commands ###
