"""Add sender_type column to message

Revision ID: 2c50bf60d56a
Revises: 9d78c551947e
Create Date: 2023-06-29 15:07:51.776931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c50bf60d56a'
down_revision = '9d78c551947e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender_type')
    # ### end Alembic commands ###
